//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizationManager.Strs {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizationManager.Strs.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ALL_LANGUAGE {
            get {
                return ResourceManager.GetString("ALL_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Custom Template과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BY_CUSTOM_TEMPLATE {
            get {
                return ResourceManager.GetString("BY_CUSTOM_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BY_LANGUAGE {
            get {
                return ResourceManager.GetString("BY_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Find Dup.Keys과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CHECK_FIND_DUP_KEYS {
            get {
                return ResourceManager.GetString("CHECK_FIND_DUP_KEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compress ZIP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COMPRESS_ZIP {
            get {
                return ResourceManager.GetString("COMPRESS_ZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   original : {0}, rename : {1} :: Duplicate Key &apos;{1}&apos; exists in {2}_{3}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DUP_KEY_EXIST_STR {
            get {
                return ResourceManager.GetString("DUP_KEY_EXIST_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicate Keys exist in Localization Data.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DUPLICATE_KEYS_EXIST_STR {
            get {
                return ResourceManager.GetString("DUPLICATE_KEYS_EXIST_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   key : {0} :: Empty Key.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EMPTY_KEY_STR {
            get {
                return ResourceManager.GetString("EMPTY_KEY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   original : {0}, rename : {1} :: Original Key is empty.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EMPTY_ORIGIN_KEY_STR {
            get {
                return ResourceManager.GetString("EMPTY_ORIGIN_KEY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   original : {0}, rename : {1} :: Rename Key is empty.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EMPTY_RENAME_KEY_STR {
            get {
                return ResourceManager.GetString("EMPTY_RENAME_KEY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tag : {0} :: Empty Tag.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EMPTY_TAG_STR {
            get {
                return ResourceManager.GetString("EMPTY_TAG_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Exist Move Key.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ERROR_EXIST_MOVE_KEY {
            get {
                return ResourceManager.GetString("ERROR_EXIST_MOVE KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Exist Remove Tag.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ERROR_EXIST_REMOVE_TAG {
            get {
                return ResourceManager.GetString("ERROR_EXIST_REMOVE TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Exist Rename Key.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ERROR_EXIST_RENAME_KEY {
            get {
                return ResourceManager.GetString("ERROR_EXIST_RENAME KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Exist Swap Key.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ERROR_EXIST_SWAP_KEY {
            get {
                return ResourceManager.GetString("ERROR_EXIST_SWAP KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EXPORT {
            get {
                return ResourceManager.GetString("EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EXPORT_ALL {
            get {
                return ResourceManager.GetString("EXPORT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export All Localization Files…과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EXPORT_ALL_LOCALIZATION_FILES {
            get {
                return ResourceManager.GetString("EXPORT_ALL_LOCALIZATION_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Category Partial과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EXPORT_CATEG_PARTIAL {
            get {
                return ResourceManager.GetString("EXPORT_CATEG_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Prefix to Json과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EXPORT_PREFIX_JSON {
            get {
                return ResourceManager.GetString("EXPORT_PREFIX_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Prefix List to Json Files…과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EXPORT_PREFIX_JSON_FILES {
            get {
                return ResourceManager.GetString("EXPORT_PREFIX_JSON_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Tag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EXPORT_TAG {
            get {
                return ResourceManager.GetString("EXPORT_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export TBT(To-be-translated)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EXPORT_TBT {
            get {
                return ResourceManager.GetString("EXPORT_TBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Dup.Keys과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FIND_DUP_KEYS {
            get {
                return ResourceManager.GetString("FIND_DUP_KEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Duplication Keys과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FIND_DUP_KEYS_STR {
            get {
                return ResourceManager.GetString("FIND_DUP_KEYS_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix Korean과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FIX_KOREAN {
            get {
                return ResourceManager.GetString("FIX_KOREAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IMPORT_FILES {
            get {
                return ResourceManager.GetString("IMPORT_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KEY {
            get {
                return ResourceManager.GetString("KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korean과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KOREAN {
            get {
                return ResourceManager.GetString("KOREAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Langauge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LANGAUGE {
            get {
                return ResourceManager.GetString("LANGAUGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load File Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOAD_FILE__TYPE {
            get {
                return ResourceManager.GetString("LOAD_FILE _TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading Localization Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOADING_LOCAL_FILES {
            get {
                return ResourceManager.GetString("LOADING_LOCAL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOCATION {
            get {
                return ResourceManager.GetString("LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage Category과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MANAGE_CATEGORY {
            get {
                return ResourceManager.GetString("MANAGE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MANAGE_LANGUAGE {
            get {
                return ResourceManager.GetString("MANAGE_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match Case과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MATCH_CASE {
            get {
                return ResourceManager.GetString("MATCH_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match whole word과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MATCH_WHOLE_WORD {
            get {
                return ResourceManager.GetString("MATCH_WHOLE_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MOVE_KEY {
            get {
                return ResourceManager.GetString("MOVE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Created TBT Only과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NEW_CREATED_TBT_ONLY {
            get {
                return ResourceManager.GetString("NEW_CREATED_TBT_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NEW_PROJECT {
            get {
                return ResourceManager.GetString("NEW_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Equals Original, Rename Key&apos;s Total Nums.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NOT_EQUAL_TOAL_KEY_NUM_STR {
            get {
                return ResourceManager.GetString("NOT_EQUAL_TOAL_KEY_NUM_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   key : {0} :: Key {0} is not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NOT_EXIST_KEY_STR {
            get {
                return ResourceManager.GetString("NOT_EXIST_KEY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tag : {0} :: Not exist Tag &apos;{0}&apos; in localData.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NOT_EXIST_TAG_STR {
            get {
                return ResourceManager.GetString("NOT_EXIST_TAG_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   original : {0}, rename : {1} :: Cannot find Key {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NOT_FIND_KEY_ORIGIN_STR {
            get {
                return ResourceManager.GetString("NOT_FIND_KEY_ORIGIN_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   original : {0}, rename : {1} :: Cannot find Key {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NOT_FIND_KEY_RENAME_STR {
            get {
                return ResourceManager.GetString("NOT_FIND_KEY_RENAME_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   key : {0} :: Cannot move Key {0} to same files.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NOT_MOVE_KEY_STR {
            get {
                return ResourceManager.GetString("NOT_MOVE_KEY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NOT_SAVE {
            get {
                return ResourceManager.GetString("NOT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OPEN_PROJECT {
            get {
                return ResourceManager.GetString("OPEN_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OPTION {
            get {
                return ResourceManager.GetString("OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Num : {0}, Rename Num : {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ORIGIN_NUM_RENAME_NUM_STR {
            get {
                return ResourceManager.GetString("ORIGIN_NUM_RENAME_NUM_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Original Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ORIGINAL_KEY {
            get {
                return ResourceManager.GetString("ORIGINAL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Partial과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PARTIAL {
            get {
                return ResourceManager.GetString("PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prefix과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PREFIX {
            get {
                return ResourceManager.GetString("PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PROJECT_NAME {
            get {
                return ResourceManager.GetString("PROJECT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regex과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string REGEX {
            get {
                return ResourceManager.GetString("REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RELOAD {
            get {
                return ResourceManager.GetString("RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Tag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string REMOVE_TAG {
            get {
                return ResourceManager.GetString("REMOVE_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RENAME_KEY {
            get {
                return ResourceManager.GetString("RENAME_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Localization data has been changed. Do you want to save All changes?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string REQUEST_SAVE_STR {
            get {
                return ResourceManager.GetString("REQUEST_SAVE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync Key&apos; has not been run. Do you want to run &apos;Sync Key&apos;?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string REQUEST_SYNC_KEY_STR {
            get {
                return ResourceManager.GetString("REQUEST_SYNC_KEY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SAVE_ALL {
            get {
                return ResourceManager.GetString("SAVE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save File Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SAVE_FILE__TYPE {
            get {
                return ResourceManager.GetString("SAVE_FILE _TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Localization Files…과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SAVE_LOCALIZATION_LOCALIZATION_FILES {
            get {
                return ResourceManager.GetString("SAVE_LOCALIZATION_LOCALIZATION_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Category, Partial과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SELECT_CATEG_PARTIAL {
            get {
                return ResourceManager.GetString("SELECT_CATEG_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SELECT_PROJECT {
            get {
                return ResourceManager.GetString("SELECT_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected Export List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SELECTED_EXPORT_LIST {
            get {
                return ResourceManager.GetString("SELECTED_EXPORT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Summary Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SET_SUMMA_INFORMATION {
            get {
                return ResourceManager.GetString("SET_SUMMA_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Translation Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SET_TRANS_STATUS {
            get {
                return ResourceManager.GetString("SET_TRANS_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} (Summary)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SUMMARY_TITLE_STR {
            get {
                return ResourceManager.GetString("SUMMARY_TITLE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swap Key과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SWAP_KEY {
            get {
                return ResourceManager.GetString("SWAP_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SYNC {
            get {
                return ResourceManager.GetString("SYNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync Key Orders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SYNC_KEY_ORDERS {
            get {
                return ResourceManager.GetString("SYNC_KEY_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronize by Key Orders…과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SYNC_KEY_ORDERS_STR {
            get {
                return ResourceManager.GetString("SYNC_KEY_ORDERS_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronize by Keys…과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SYNC_KEY_STR {
            get {
                return ResourceManager.GetString("SYNC_KEY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync Keys과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SYNC_KEYS {
            get {
                return ResourceManager.GetString("SYNC_KEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync Keys Completed!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SYNC_KEYS__COMPLETE_STR {
            get {
                return ResourceManager.GetString("SYNC_KEYS _COMPLETE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronize과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SYNCHRONIZE {
            get {
                return ResourceManager.GetString("SYNCHRONIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TAG {
            get {
                return ResourceManager.GetString("TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TOOL {
            get {
                return ResourceManager.GetString("TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VALUE {
            get {
                return ResourceManager.GetString("VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
    }
}
